#spring.application.name=demo
#
#server.host=http://localhost:8080/
#server.port=8080
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=adminadmin
#
#logging.level.org.hibernate.SQL=debug

server.host=http://localhost:8040
server.port=8040
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:postgresql://localhost:5432/planer_database
spring.datasource.username=user
spring.datasource.password=secrete}

logging.level.org.hibernate.SQL=debug
