server.host=http://localhost:8040
server.port=8040
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:postgresql://localhost:5432/planer_database_test
spring.datasource.username=user
spring.datasource.password=secrete}

logging.level.org.hibernate.SQL=debug
